version: '3'
services:
  nginx:
    image: nginx
    container_name: mine-h5-ui
    build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/logs:/var/log/nginx
      - /docker/nginx/certs:/etc/nginx/cert
      - /docker/nginx/config:/etc/nginx/config
