name: Publish Package To NpmJs

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build:theme
      - run: npm run build:package
      - run: npm run pre-publish
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          cd dist/packages
          if [[ "$VERSION" == *"beta"* ]]; then
            npm publish --tag=beta-v2
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
