name: Release Log

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
      - name: check
        - uses: actions/setup-node@v4
        - run: |
            VERSION=$(node -p "require('./package.json').version")
            if [[ "$VERSION" == *"beta"* ]]; then
              exit 0;
            fi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: log.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}